config:
  batch_size: 1024
  epochs: 100
  lr: 0.15
  channels: 3
  num_workers: 4
  num_classes: 1000
  data_dir: '/mnt/disks/vit-data-disk/imagenet_64'
  dataset: 'imagenet_contrastive'
  log_steps: 100
  drop_last: True
  scheduler: 'cosine_with_warmup'
  weight_decay: 0.
  nprocs: 8
  alpha_mixup: 0.0
  warmup_steps: 15000
  dropout: 0.
