config:
  batch_size: 1024
  epochs: 30
  lr: 1.e-4
  channels: 3
  num_workers: 4
  num_classes: 1000
  data_dir: '/mnt/disks/vit-data-disk/imagenet_64'
  dataset: 'imagenet'
  log_steps: 100
  drop_last: False
  scheduler: 'cosine_with_warmup'
  weight_decay: 0.01
  nprocs: 8
  warmup_steps: 1000
  alpha_mixup: 0.0
  dropout: 0.
